name: "coverage"
on:
  pull_request:
    branches:
      - main
jobs:
  coverage:
    if: github.event.pull_request.head.repo.fork == false
    permissions:
      checks: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          test-script: npm test
